'use client';

import { Box } from '@chakra-ui/react';
import { Providers } from './Providers';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Box maxW="5xl" mx="auto">
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  );
}
